#############################################################################
# Makefile for building: main
# Generated by qmake (2.01a) (Qt 4.5.2) on: sáb mar 27 02:48:03 2010
# Project:  main.pro
# Template: subdirs
# Command: /usr/bin/qmake -unix -o Makefile main.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-myQPushButtonPlugin \
		sub-myQLCDNumberPlugin \
		sub-myForm

myQPushButtonPlugin//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) myQPushButtonPlugin/ || $(MKDIR) myQPushButtonPlugin/ 
	cd myQPushButtonPlugin/ && $(QMAKE) myQPushButtonPlugin.pro -unix -o $(MAKEFILE)
sub-myQPushButtonPlugin-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) myQPushButtonPlugin/ || $(MKDIR) myQPushButtonPlugin/ 
	cd myQPushButtonPlugin/ && $(QMAKE) myQPushButtonPlugin.pro -unix -o $(MAKEFILE)
sub-myQPushButtonPlugin: myQPushButtonPlugin//$(MAKEFILE) FORCE
	cd myQPushButtonPlugin/ && $(MAKE) -f $(MAKEFILE)
sub-myQPushButtonPlugin-make_default-ordered: myQPushButtonPlugin//$(MAKEFILE) FORCE
	cd myQPushButtonPlugin/ && $(MAKE) -f $(MAKEFILE) 
sub-myQPushButtonPlugin-make_default: myQPushButtonPlugin//$(MAKEFILE) FORCE
	cd myQPushButtonPlugin/ && $(MAKE) -f $(MAKEFILE) 
sub-myQPushButtonPlugin-make_first-ordered: myQPushButtonPlugin//$(MAKEFILE) FORCE
	cd myQPushButtonPlugin/ && $(MAKE) -f $(MAKEFILE) first
sub-myQPushButtonPlugin-make_first: myQPushButtonPlugin//$(MAKEFILE) FORCE
	cd myQPushButtonPlugin/ && $(MAKE) -f $(MAKEFILE) first
sub-myQPushButtonPlugin-all-ordered: myQPushButtonPlugin//$(MAKEFILE) FORCE
	cd myQPushButtonPlugin/ && $(MAKE) -f $(MAKEFILE) all
sub-myQPushButtonPlugin-all: myQPushButtonPlugin//$(MAKEFILE) FORCE
	cd myQPushButtonPlugin/ && $(MAKE) -f $(MAKEFILE) all
sub-myQPushButtonPlugin-clean-ordered: myQPushButtonPlugin//$(MAKEFILE) FORCE
	cd myQPushButtonPlugin/ && $(MAKE) -f $(MAKEFILE) clean
sub-myQPushButtonPlugin-clean: myQPushButtonPlugin//$(MAKEFILE) FORCE
	cd myQPushButtonPlugin/ && $(MAKE) -f $(MAKEFILE) clean
sub-myQPushButtonPlugin-distclean-ordered: myQPushButtonPlugin//$(MAKEFILE) FORCE
	cd myQPushButtonPlugin/ && $(MAKE) -f $(MAKEFILE) distclean
sub-myQPushButtonPlugin-distclean: myQPushButtonPlugin//$(MAKEFILE) FORCE
	cd myQPushButtonPlugin/ && $(MAKE) -f $(MAKEFILE) distclean
sub-myQPushButtonPlugin-install_subtargets-ordered: myQPushButtonPlugin//$(MAKEFILE) FORCE
	cd myQPushButtonPlugin/ && $(MAKE) -f $(MAKEFILE) install
sub-myQPushButtonPlugin-install_subtargets: myQPushButtonPlugin//$(MAKEFILE) FORCE
	cd myQPushButtonPlugin/ && $(MAKE) -f $(MAKEFILE) install
sub-myQPushButtonPlugin-uninstall_subtargets-ordered: myQPushButtonPlugin//$(MAKEFILE) FORCE
	cd myQPushButtonPlugin/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-myQPushButtonPlugin-uninstall_subtargets: myQPushButtonPlugin//$(MAKEFILE) FORCE
	cd myQPushButtonPlugin/ && $(MAKE) -f $(MAKEFILE) uninstall
myQLCDNumberPlugin//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) myQLCDNumberPlugin/ || $(MKDIR) myQLCDNumberPlugin/ 
	cd myQLCDNumberPlugin/ && $(QMAKE) myQLCDNumberPlugin.pro -unix -o $(MAKEFILE)
sub-myQLCDNumberPlugin-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) myQLCDNumberPlugin/ || $(MKDIR) myQLCDNumberPlugin/ 
	cd myQLCDNumberPlugin/ && $(QMAKE) myQLCDNumberPlugin.pro -unix -o $(MAKEFILE)
sub-myQLCDNumberPlugin: myQLCDNumberPlugin//$(MAKEFILE) FORCE
	cd myQLCDNumberPlugin/ && $(MAKE) -f $(MAKEFILE)
sub-myQLCDNumberPlugin-make_default-ordered: myQLCDNumberPlugin//$(MAKEFILE) sub-myQPushButtonPlugin-make_default-ordered  FORCE
	cd myQLCDNumberPlugin/ && $(MAKE) -f $(MAKEFILE) 
sub-myQLCDNumberPlugin-make_default: myQLCDNumberPlugin//$(MAKEFILE) FORCE
	cd myQLCDNumberPlugin/ && $(MAKE) -f $(MAKEFILE) 
sub-myQLCDNumberPlugin-make_first-ordered: myQLCDNumberPlugin//$(MAKEFILE) sub-myQPushButtonPlugin-make_first-ordered  FORCE
	cd myQLCDNumberPlugin/ && $(MAKE) -f $(MAKEFILE) first
sub-myQLCDNumberPlugin-make_first: myQLCDNumberPlugin//$(MAKEFILE) FORCE
	cd myQLCDNumberPlugin/ && $(MAKE) -f $(MAKEFILE) first
sub-myQLCDNumberPlugin-all-ordered: myQLCDNumberPlugin//$(MAKEFILE) sub-myQPushButtonPlugin-all-ordered  FORCE
	cd myQLCDNumberPlugin/ && $(MAKE) -f $(MAKEFILE) all
sub-myQLCDNumberPlugin-all: myQLCDNumberPlugin//$(MAKEFILE) FORCE
	cd myQLCDNumberPlugin/ && $(MAKE) -f $(MAKEFILE) all
sub-myQLCDNumberPlugin-clean-ordered: myQLCDNumberPlugin//$(MAKEFILE) sub-myQPushButtonPlugin-clean-ordered  FORCE
	cd myQLCDNumberPlugin/ && $(MAKE) -f $(MAKEFILE) clean
sub-myQLCDNumberPlugin-clean: myQLCDNumberPlugin//$(MAKEFILE) FORCE
	cd myQLCDNumberPlugin/ && $(MAKE) -f $(MAKEFILE) clean
sub-myQLCDNumberPlugin-distclean-ordered: myQLCDNumberPlugin//$(MAKEFILE) sub-myQPushButtonPlugin-distclean-ordered  FORCE
	cd myQLCDNumberPlugin/ && $(MAKE) -f $(MAKEFILE) distclean
sub-myQLCDNumberPlugin-distclean: myQLCDNumberPlugin//$(MAKEFILE) FORCE
	cd myQLCDNumberPlugin/ && $(MAKE) -f $(MAKEFILE) distclean
sub-myQLCDNumberPlugin-install_subtargets-ordered: myQLCDNumberPlugin//$(MAKEFILE) sub-myQPushButtonPlugin-install_subtargets-ordered  FORCE
	cd myQLCDNumberPlugin/ && $(MAKE) -f $(MAKEFILE) install
sub-myQLCDNumberPlugin-install_subtargets: myQLCDNumberPlugin//$(MAKEFILE) FORCE
	cd myQLCDNumberPlugin/ && $(MAKE) -f $(MAKEFILE) install
sub-myQLCDNumberPlugin-uninstall_subtargets-ordered: myQLCDNumberPlugin//$(MAKEFILE) sub-myQPushButtonPlugin-uninstall_subtargets-ordered  FORCE
	cd myQLCDNumberPlugin/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-myQLCDNumberPlugin-uninstall_subtargets: myQLCDNumberPlugin//$(MAKEFILE) FORCE
	cd myQLCDNumberPlugin/ && $(MAKE) -f $(MAKEFILE) uninstall
myForm//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) myForm/ || $(MKDIR) myForm/ 
	cd myForm/ && $(QMAKE) myForm.pro -unix -o $(MAKEFILE)
sub-myForm-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) myForm/ || $(MKDIR) myForm/ 
	cd myForm/ && $(QMAKE) myForm.pro -unix -o $(MAKEFILE)
sub-myForm: myForm//$(MAKEFILE) FORCE
	cd myForm/ && $(MAKE) -f $(MAKEFILE)
sub-myForm-make_default-ordered: myForm//$(MAKEFILE) sub-myQLCDNumberPlugin-make_default-ordered  FORCE
	cd myForm/ && $(MAKE) -f $(MAKEFILE) 
sub-myForm-make_default: myForm//$(MAKEFILE) FORCE
	cd myForm/ && $(MAKE) -f $(MAKEFILE) 
sub-myForm-make_first-ordered: myForm//$(MAKEFILE) sub-myQLCDNumberPlugin-make_first-ordered  FORCE
	cd myForm/ && $(MAKE) -f $(MAKEFILE) first
sub-myForm-make_first: myForm//$(MAKEFILE) FORCE
	cd myForm/ && $(MAKE) -f $(MAKEFILE) first
sub-myForm-all-ordered: myForm//$(MAKEFILE) sub-myQLCDNumberPlugin-all-ordered  FORCE
	cd myForm/ && $(MAKE) -f $(MAKEFILE) all
sub-myForm-all: myForm//$(MAKEFILE) FORCE
	cd myForm/ && $(MAKE) -f $(MAKEFILE) all
sub-myForm-clean-ordered: myForm//$(MAKEFILE) sub-myQLCDNumberPlugin-clean-ordered  FORCE
	cd myForm/ && $(MAKE) -f $(MAKEFILE) clean
sub-myForm-clean: myForm//$(MAKEFILE) FORCE
	cd myForm/ && $(MAKE) -f $(MAKEFILE) clean
sub-myForm-distclean-ordered: myForm//$(MAKEFILE) sub-myQLCDNumberPlugin-distclean-ordered  FORCE
	cd myForm/ && $(MAKE) -f $(MAKEFILE) distclean
sub-myForm-distclean: myForm//$(MAKEFILE) FORCE
	cd myForm/ && $(MAKE) -f $(MAKEFILE) distclean
sub-myForm-install_subtargets-ordered: myForm//$(MAKEFILE) sub-myQLCDNumberPlugin-install_subtargets-ordered  FORCE
	cd myForm/ && $(MAKE) -f $(MAKEFILE) install
sub-myForm-install_subtargets: myForm//$(MAKEFILE) FORCE
	cd myForm/ && $(MAKE) -f $(MAKEFILE) install
sub-myForm-uninstall_subtargets-ordered: myForm//$(MAKEFILE) sub-myQLCDNumberPlugin-uninstall_subtargets-ordered  FORCE
	cd myForm/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-myForm-uninstall_subtargets: myForm//$(MAKEFILE) FORCE
	cd myForm/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: main.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -unix -o Makefile main.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -unix -o Makefile main.pro

qmake_all: sub-myQPushButtonPlugin-qmake_all sub-myQLCDNumberPlugin-qmake_all sub-myForm-qmake_all FORCE

make_default: sub-myQPushButtonPlugin-make_default-ordered sub-myQLCDNumberPlugin-make_default-ordered sub-myForm-make_default-ordered FORCE
make_first: sub-myQPushButtonPlugin-make_first-ordered sub-myQLCDNumberPlugin-make_first-ordered sub-myForm-make_first-ordered FORCE
all: sub-myQPushButtonPlugin-all-ordered sub-myQLCDNumberPlugin-all-ordered sub-myForm-all-ordered FORCE
clean: sub-myQPushButtonPlugin-clean-ordered sub-myQLCDNumberPlugin-clean-ordered sub-myForm-clean-ordered FORCE
distclean: sub-myQPushButtonPlugin-distclean-ordered sub-myQLCDNumberPlugin-distclean-ordered sub-myForm-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-myQPushButtonPlugin-install_subtargets-ordered sub-myQLCDNumberPlugin-install_subtargets-ordered sub-myForm-install_subtargets-ordered FORCE
uninstall_subtargets: sub-myQPushButtonPlugin-uninstall_subtargets-ordered sub-myQLCDNumberPlugin-uninstall_subtargets-ordered sub-myForm-uninstall_subtargets-ordered FORCE

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

